# Generated by Django 6.0.3 on 2026-06-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_send_private_email', 'Can send private email to customers by the button')]},
        ),
    ]
